bugfix/header
DenisMuss/landing-product pull request #3
Opened 2024-07-18 15:01 UTC by DenisMuss

2024-07-18 20:33 UTC, kkiirill commented on index.html
> +		<title></title>
Add title for your website

2024-07-18 20:33 UTC, kkiirill commented on index.html
> +		<body>
body must be under head
<head>
</head>
<body>
</body>

2024-07-18 20:33 UTC, kkiirill commented on index.html
> +					<nav class="nav">
span
under
nav

2024-07-18 20:33 UTC, kkiirill commented on index.html
> +						<ul class="ul">
replace class ul to nav-list

2024-07-18 20:33 UTC, kkiirill commented on index.html
> +							<li class="Home"><a href="#">Home</a></li>
what is class "Home"?

you need to add class to all link

name  class "nav-link"

2024-07-18 20:33 UTC, kkiirill commented on style.css
> +    --orange: #DC7000;
orange-color

2024-07-18 20:33 UTC, kkiirill commented on style.css
> +    --orange: #DC7000;
write on lower case dc70000

2024-07-18 20:33 UTC, kkiirill commented on style.css
> +    padding: 0%;
just 0

2024-07-18 20:33 UTC, kkiirill commented on style.css
> +    margin: 0%;
just 0

2024-07-18 20:33 UTC, kkiirill commented on style.css
> -.nav ul li{
It's not a good practice

you need create class nav-link and remove this nav ul li 

read this https://developer.mozilla.org/ru/docs/Web/CSS/Specificity

2024-07-18 20:33 UTC, kkiirill commented on style.css
> +.ul li a {
not good practice use class

2024-07-18 20:33 UTC, kkiirill commented on style.css
> +.Home {
you need to add this class not only for the first element. If you see multiple elements in a design and one element with an additional color/border etc., that means you need to add this functionality to all elements, but on hover

use hover 
read about it https://developer.mozilla.org/ru/docs/Web/CSS/Pseudo-classes
https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Selectors/Pseudo-classes_and_pseudo-elements

2024-07-18 20:33 UTC, kkiirill commented on style.css
>      position: relative;
don't need this

2024-07-18 20:33 UTC, kkiirill commented on style.css
> +    width: 82px;
Logo it's just text?
width and height doesn't need this

2024-07-18 20:44 UTC, DenisMuss commented on index.html
> +		<title></title>
![1](https://github.com/user-attachments/assets/9172d4db-812c-4a32-9038-8b2ceb1f64ac)

2024-07-18 20:46 UTC, DenisMuss commented on index.html
> +		<body>
![2](https://github.com/user-attachments/assets/790a7399-f554-4ddd-abcb-1c117336f20b)

2024-07-21 08:41 UTC, DenisMuss commented on index.html
> +					<nav class="nav">
![3](https://github.com/user-attachments/assets/ef5d7bd4-02d6-4b0f-8625-adfe6a924b6c)

2024-07-21 08:42 UTC, DenisMuss commented on index.html
> +						<ul class="ul">
![4](https://github.com/user-attachments/assets/f64ce606-517b-4d85-bd7d-9ab58c574e9d)

2024-07-21 08:42 UTC, DenisMuss commented on index.html
> +					<nav class="nav">
under???

2024-07-21 08:46 UTC, DenisMuss commented on index.html
> +							<li class="Home"><a href="#">Home</a></li>
![6](https://github.com/user-attachments/assets/43551649-69c1-453c-9f54-003cf3a35575)

2024-07-21 08:48 UTC, DenisMuss commented on style.css
> +    --orange: #DC7000;
![7](https://github.com/user-attachments/assets/1d501c88-e3e7-4663-bdf0-f3d749725253)

2024-07-21 08:50 UTC, DenisMuss commented on style.css
> +    padding: 0%;
![8](https://github.com/user-attachments/assets/2be8e5df-b751-465e-ba48-99a1daf1a5ca)

2024-07-21 08:50 UTC, DenisMuss commented on style.css
> +    margin: 0%;
corrected

2024-07-21 10:28 UTC, DenisMuss commented on style.css
> -.nav ul li{
![10](https://github.com/user-attachments/assets/8ceb2c63-083d-4a4a-a26e-1413d56decdc)

2024-07-21 10:28 UTC, DenisMuss commented on style.css
> -.nav ul li{
![11](https://github.com/user-attachments/assets/e704d59b-71c7-4cec-bbae-35abcf51cfea)

2024-07-21 10:29 UTC, DenisMuss commented on style.css
> +.ul li a {
fixed

2024-07-21 10:30 UTC, DenisMuss commented on style.css
> -.nav ul li{
![10](https://github.com/user-attachments/assets/98d33d9f-f881-4c3d-a669-855b8609e189)
![11](https://github.com/user-attachments/assets/15281f86-cfbd-4d25-bc67-8a04ec14db6a)

2024-07-21 10:31 UTC, DenisMuss commented on style.css
> +.ul li a {
fixed

2024-07-21 10:37 UTC, DenisMuss commented on style.css
> +.Home {
i used id on the link with a class

2024-07-21 10:38 UTC, DenisMuss commented on style.css
>      position: relative;
![12](https://github.com/user-attachments/assets/9fcc54f0-e729-4571-a4eb-8e0c6d94c04b)

2024-07-21 10:40 UTC, DenisMuss commented on style.css
> +    width: 82px;
![13](https://github.com/user-attachments/assets/540cc9e8-5f1a-4502-ace5-d14af1d8d5b4)

2024-07-21 11:57 UTC, kkiirill commented on index.html
> +						<li class="nav-link" id="Contact"><a href="#">Contact us</a></li>
why we need id=Contact?

2024-07-21 11:57 UTC, kkiirill commented on style.css
> +.ul-list {
it's not good practice naming ul li div etc - best use this naming nav-list

2024-07-21 11:57 UTC, kkiirill commented on style.css
> +.nav-link a {
we don't need use "a" if we already use .nav-link

2024-07-21 11:57 UTC, kkiirill commented on style.css
> +#Home {
why we need this?

2024-07-21 11:57 UTC, kkiirill commented on style.css
> +#Contact {
not use id for this use class

2024-07-21 12:53 UTC, kkiirill approved these changes

2024-07-21 12:54 UTC, kkiirill requested changes
LGTM

2024-07-21 12:55 UTC, kkiirill approved these changes
Approve

2024-07-21 12:59 UTC, merged